# Generated by Django 5.0 on 2025-09-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_petition'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
