# Generated by Django 5.2.6 on 2025-10-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_userlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=3),
        ),
    ]
