# Generated by Django 5.0 on 2025-10-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_review_reviewcount_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewCount',
        ),
        migrations.AddField(
            model_name='movie',
            name='reviewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
