# Generated by Django 5.0 on 2025-10-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_review_rating'),
        ('movies', '0010_remove_review_reviewcount_movie_reviewcount_and_more'),
    ]

    operations = [
    ]
